module.exports = {
  config: {
    name: "lyricalvideo",
    aliases: ["lv", "lyricsvideo", "lyricaledit"],
    version: "1.0",
    author: "kshitiz",
    countDown: 20,
    role: 0,
    shortDescription: "get lyrical video",
    longDescription: "it will send you lyrical video from lyrics edit vibe group",
    category: "music",
    guide: "{pn} lyricalvideo",
  },

  sentVideos: [],

  onStart: async function ({ api, event, message }) {
    const senderID = event.senderID;

    const loadingMessage = await message.reply({
      body: "Loading random lyrical video... Please wait! 🕐",
    });

    const link = [
      "https://drive.google.com/uc?export=download&id=1xdoZpGGd1iC9zkTHojL-uh_Xu8pp8LwJ",// video credits lyrics edit vibe (fb group)
      "https://drive.google.com/uc?export=download&id=1RNZhamE4ArtjdsCvbeBWtIzhRYmMbG6z",
      "https://drive.google.com/uc?export=download&id=13cYUnYi9_hHY4-wRUqV6z3gtRci88A5I",
      "https://drive.google.com/uc?export=download&id=1tR-12BqyCccyMGqMa-OLYrBB0YkqBigX",
      "https://drive.google.com/uc?export=download&id=1MCyv1IIw1nQk96hBa6faJLQXVps2NDB1",
      "https://drive.google.com/uc?export=download&id=1ZYYStznq6rWQ4m8FcGs8CS1mp_mHHE89",
      "https://drive.google.com/uc?export=download&id=1D-1iO7nO-Nlcie3uUAluPaI53yRarCdE",
      "https://drive.google.com/uc?export=download&id=1Pk27Z4LX2y2rHcvtY5VJiF9hJoowY9HR",
      "https://drive.google.com/uc?export=download&id=1FBJ6kZFZPmYZSk3vHz7ECfqdA4yhF2k0",
      "https://drive.google.com/uc?export=download&id=1md55_KQdoTX4HWW6n0RM7AbBfW8XPyGN",
      "https://drive.google.com/uc?export=download&id=1KCYrHH1lISPWbA8q7kLX8G7BUsJhlqw9",
      "https://drive.google.com/uc?export=download&id=1NYxXQ7UmVjcTdY27WePCJ8iW6HC_l-Ej",
      "https://drive.google.com/uc?export=download&id=1SC9OnQcXlkRGt1auBgV_Ez9itpYG2ixh",
      "https://drive.google.com/uc?export=download&id=1D_ODRaSij_KQemlzrQS9B-h3RM6yZ680",
      "https://drive.google.com/uc?export=download&id=1fZgMyISANhpOLcfo5HVht5OKolhrHQoD",
      "https://drive.google.com/uc?export=download&id=1glf5NdpxDWcfPVyQdYv1HleNmJ6-8WN8",
      "https://drive.google.com/uc?export=download&id=1trMuw_ezC58iMwR4umtRKzRdK0_VsI7Y",
      "https://drive.google.com/uc?export=download&id=1mDCJvrIUHfPgi1CH-xTxSZbaOQPXfF8S",
      "https://drive.google.com/uc?export=download&id=1mNKuaSICDDGL8pq26oR07nIFVWfTCjpu",
      "https://drive.google.com/uc?export=download&id=1oX2VgqglgDilll77xURzPTrvwEjx5B4e",
      "https://drive.google.com/uc?export=download&id=1usstpJwO6NkxCQiPiEW9yj0H4julH0kO",
      "https://drive.google.com/uc?export=download&id=1VLGzoJM52Q8WYviX6DLg9okDRd16lE75",
      "https://drive.google.com/uc?export=download&id=1IGUZduyBGTGSq27gkxiLRkuHYNjC7fXv",
      "https://drive.google.com/uc?export=download&id=1IGUZduyBGTGSq27gkxiLRkuHYNjC7fXv",
      "https://drive.google.com/uc?export=download&id=1Jgiy1cI4CIpZeHL3-YaUgcX1UzahaDwN",
      "https://drive.google.com/uc?export=download&id=1sIH4GwHfpny684720z1gFulQCbbjCuQo",
      "https://drive.google.com/uc?export=download&id=1E1G1ecSy_DyOWmQPVJI8EIWFcerdfsqt",
      "https://drive.google.com/uc?export=download&id=1zKzL9yoHasu5R2sii2cJLomB81e3liYp",
      "https://drive.google.com/uc?export=download&id=1q51lljCcR_V7uCR_Umhst-2mnUpjriOA",
      "https://drive.google.com/uc?export=download&id=1TVKeHZuGWY3qVkNtXM53Uploac4uAGPr",
      "https://drive.google.com/uc?export=download&id=1fMk8VvH5w-FsIZC2kcB895DZiu1I9XOh",
      "https://drive.google.com/uc?export=download&id=1_4PSnfa4fhnXCZI8OgTYE55jgnUJjlPF",
      "https://drive.google.com/uc?export=download&id=1A2ODenh6zIXGKyOFMwAgWjnuPVzvnynJ",
      "https://drive.google.com/uc?export=download&id=19lqOz0X7AD7-NEXtrSUDR3wR23yOXZ50",
      "https://drive.google.com/uc?export=download&id=1A5GBE8n7cf-yGqGld8aSs-XH_KnLw5dH",
      "https://drive.google.com/uc?export=download&id=1A0AArSzPLEPb97RAVxzLj31e2kj5nsng",
      "https://drive.google.com/uc?export=download&id=18NZdfVvl5s7mmUn5CLNrp01a1FElGNnf",
      "https://drive.google.com/uc?export=download&id=19HDrVFvfucxwJp-jj4kM2y7l1EQSnASJ",
      "https://drive.google.com/uc?export=download&id=18Npt8nIYXO1U5NxStVc3lSGHJwVmeN5X",
      "https://drive.google.com/uc?export=download&id=18Npt8nIYXO1U5NxStVc3lSGHJwVmeN5X",
      "https://drive.google.com/uc?export=download&id=19mqNuC27aOOf5xy4B_cOG7W6stXHRzZk",
      "https://drive.google.com/uc?export=download&id=19zPRVVsggM9BrNy_29XYZyynorUaCKjs",
      "https://drive.google.com/uc?export=download&id=1AQaugSzhoeAel0oMnufbN9VKYQVyixb2",
      "https://drive.google.com/uc?export=download&id=1A7iERNZgbq79MoQdJOapkY3KCkgGlB-r",
      "https://drive.google.com/uc?export=download&id=11BKiK_walhjdbj5flOK-mup5OgIoUUxD",
      "https://drive.google.com/uc?export=download&id=1T2taH3NRhpyPv9k6GcyZlnXpppurdh9Q",
      "https://drive.google.com/uc?export=download&id=1k3-5p6Ztada4jlq1-F2IqiulF85N1Gi_",
      "https://drive.google.com/uc?export=download&id=1pPGVwrgXaJSI7qZUWceuR-opoJG7e9pQ",
      "https://drive.google.com/uc?export=download&id=1BS0tQ8Izj58ovY9AxuAAEOo1nNFQJKDD",
      "https://drive.google.com/uc?export=download&id=15SSw9s82Ew_JKB91Fj1H-Wx5pkNimwJS",
      "https://drive.google.com/uc?export=download&id=1HdeX8SDFMc1LFIP9ZlFId0YhAduVFgDZ",
      "https://drive.google.com/uc?export=download&id=1o-Iuc5AV-BNum22QiMLqczBrGcIrL9xs",
      "https://drive.google.com/uc?export=download&id=1Rkg45T5JQu_wM-dpyQuq8WaZCjk8DuAh",
      "https://drive.google.com/uc?export=download&id=1YbWl_Ho147Lg0kfHxUzFZcaO4VjmKNCX",
      "https://drive.google.com/uc?export=download&id=1fLnHrlE5YCv8yHdxGu_P7xqHRFmcMsAQ",
      "https://drive.google.com/uc?export=download&id=16MvwDvg57x5FIUcK_AKBcv1AmVTg4Fyz",
      "https://drive.google.com/uc?export=download&id=1tCBoUOHGpmQjN53OiOUGWODrMnmvdwPT",
      "https://drive.google.com/uc?export=download&id=1S8XilQLVBM4kTNuWQE0KhLTOVMAgrQYL",
      "https://drive.google.com/uc?export=download&id=17tWryBlk3zFbsn1vrJzt7GWT56PKfQAJ",
      "https://drive.google.com/uc?export=download&id=1F3LsUW-hD8WvFbjqp1a9tb2QJ49BcA9Q",
      "https://drive.google.com/uc?export=download&id=14cC6V52SsN2t3pX1lCTb0onPFRGTRCa_",
      "https://drive.google.com/uc?export=download&id=1DdJGIecb5GK2A1yJXTPjHH9hpIhsKCfx",
      "https://drive.google.com/uc?export=download&id=15cVezpny2P4iKdt_N3yHnIGj37Dpneh_",
      "https://drive.google.com/uc?export=download&id=1N6ZDDlChmuS2LH0B9TkaiFbNZZt0Zd96",
      "https://drive.google.com/uc?export=download&id=1RLu6EnaxCqmksNAVxn-X8BofV-qISmtA",
      "https://drive.google.com/uc?export=download&id=11SKe8gRkLZ-YY_7t8oWK6nbO4SOS45aN",
      "https://drive.google.com/uc?export=download&id=1hZ0m0mCKMxwZarNA1mi9_RXt9XhAxYS-",
      "https://drive.google.com/uc?export=download&id=1305HBw0refYVQ0NkoOobq2EOTWEgRFkY",
      "https://drive.google.com/uc?export=download&id=1WN7lw5lLFP20a91LcYaPa-GQvgD-hTiH",
      "https://drive.google.com/uc?export=download&id=1z3k7-tTo2BOW2KC1zocHbPnTShrRMvuy",
      "https://drive.google.com/uc?export=download&id=1qd6VfUUlA0Lz2G8URmpW83mnoMp7x4FH",
      "https://drive.google.com/uc?export=download&id=1gP_gdzi_duFpMuJ5yIMDzxBHLxjD7KfF",
      "https://drive.google.com/uc?export=download&id=1f8BuRtjl6Kn1SQ9CCf-hqZJT3IEiDAMz",
      "https://drive.google.com/uc?export=download&id=1oE-zuYm9HCIZZz59gIEgsR33X8PaT9w4",
      "https://drive.google.com/uc?export=download&id=19yqoToQH9YRCq0K47BfK-ktbmYzZkXCy",
      "https://drive.google.com/uc?export=download&id=1XlGmGeVYb_82Xo2ni92iS8otYESRhjc7",
      "https://drive.google.com/uc?export=download&id=1Cz0DpSGcqmvd4Cqn29SVn7T53aYkj9cq",
      "https://drive.google.com/uc?export=download&id=1eMSrzSz6-pXblA4R-KizNo2kUfQrGGo0",
      "https://drive.google.com/uc?export=download&id=1hl1c2fLupZE_j6SOBy5VIK1qCHu4hdWH",
      "https://drive.google.com/uc?export=download&id=1HlEMGyEfDu8kPW3cw4QAhaz6PLU6gLOh",
      "https://drive.google.com/uc?export=download&id=13iiT-5nMKqFZg6d60uIrzTdYY6mZaG0V",
      "https://drive.google.com/uc?export=download&id=1WBqWf986rhT52rBmzCHDxFagjoJw50cu",
      "https://drive.google.com/uc?export=download&id=1gGLGkvVz9d4rOuzR9-O-SvRBKmNWu08T",
      "https://drive.google.com/uc?export=download&id=1-RdOA1WdJzuGyWFCmGINDDE8XH_8NDOp",
      "https://drive.google.com/uc?export=download&id=1a9scbBxtX1UU64JGE7I-OAP5PLD5eau2",
      "https://drive.google.com/uc?export=download&id=1qz25P1RB0ivLfFSNHPD9HM0q3DWUzbRb",
      "https://drive.google.com/uc?export=download&id=1JQTtAzOm2e1Q4PdCBIL8sd18eCVmf3lS",
      "https://drive.google.com/uc?export=download&id=1QZ0VtiRutnLrUNtqFpZvB9FBoCkyW69I",
      "https://drive.google.com/uc?export=download&id=1vrsGVwdPPaJ0-w3tOwQP8ay5wz4hQviv",
      "https://drive.google.com/uc?export=download&id=1MsiiAtXdeSN20RYsEs27lY-OplZ04b1i",
      "https://drive.google.com/uc?export=download&id=1sIir3HhbBHbFbuRiN9S3ql09z5dFE_O0",
      "https://drive.google.com/uc?export=download&id=1w2HOc1oVBvOg1looLT2bG8wUnTGiIse5",
      "https://drive.google.com/uc?export=download&id=1tk0wQfmAHjvaZQgVHH26-reE_OOpHWS0",
      "https://drive.google.com/uc?export=download&id=1pxtZnZTBlxi5R2UOuEsnwj_L8ALN1_s-",
      "https://drive.google.com/uc?export=download&id=1FAsCpN81lNFsJ5hZVQLjj1IqxaKRqMMW",
      "https://drive.google.com/uc?export=download&id=165vcnw4LWBT9jdTZmcFpWt_7hKcVSpsr",
      "https://drive.google.com/uc?export=download&id=1ZrqCO5AhAYnhPGQ1Gp4MJEzWLQ2akgkh",
      "https://drive.google.com/uc?export=download&id=1Lg3IlF9-KanVw4wuSEmcvKfsQqTtKM2G",
      "https://drive.google.com/uc?export=download&id=1b2bL3zfkcbCcQRwbvcSY0wI4t3HRJoGK",
      "https://drive.google.com/uc?export=download&id=1XTTs0Inti6GWBln7a6L10I7PJLuIWXFy",
      "https://drive.google.com/uc?export=download&id=1DVgcObXACEVUXAHwZMTyN39d1QBHK3eC",
      "https://drive.google.com/uc?export=download&id=1J6l_S_-Xt4b5KeU7MWkCFfbwftVbiENa",
      "https://drive.google.com/uc?export=download&id=13diMuYAVa99eO7GVS_OtZ4CfsVAd0E48",
      "https://drive.google.com/uc?export=download&id=1Chne4lr3NkAGtm31Qbxh2EWHomj75_Ma",
      "https://drive.google.com/uc?export=download&id=1bVdNL2MsJQ3JdKA4bx-8kKGxmxgxQn71",
      "https://drive.google.com/uc?export=download&id=10m0EL9COdCyBSrvdVK3iblTutu4tzRi6",
      "https://drive.google.com/uc?export=download&id=1UECWqt86xn_NkuHFUEeUkOtrYqlC46Av",
      "https://drive.google.com/uc?export=download&id=1m7D4a15641FW3513ZO_-CeJ3wKRZ27EH",
      "https://drive.google.com/uc?export=download&id=1Ey3vk4SBGbn3xvrqAGBLfC5x7MAM7stK",
      "https://drive.google.com/uc?export=download&id=16hudg17uX8-dZy5IVnh05GaqoNpPKgKr",
      "https://drive.google.com/uc?export=download&id=1OtgC2ngELtEXORixsByL1Ybqh5GctgQ4",
      "https://drive.google.com/uc?export=download&id=1uGsaWFbEjmDbzANGsGWxRpAtAnsEhAea",
      "https://drive.google.com/uc?export=download&id=1BUSrp6oHTSGauamWn5E5ZtmnmPJ-L-LH",
      "https://drive.google.com/uc?export=download&id=1ZLxdXrjGKUwe3mUA8DFwrzrp_lRzGrj5",
      "https://drive.google.com/uc?export=download&id=1_2kM9E1mpcq4VGVsYWKWmczNlTN6Hlio",
      "https://drive.google.com/uc?export=download&id=1gaLR5mTXGmerWhu3rMqdQ_gak0Igq5IE",
      "https://drive.google.com/uc?export=download&id=1m0IQx_MxPaVuKgFfu-alzx-UquNPnsvl",
      "https://drive.google.com/uc?export=download&id=1ICZdMRgAzccFnRoTVa8q5Yn8filjAZ4b",
      "https://drive.google.com/uc?export=download&id=1DM1IaxJ6CeQ8RS-cqCEnvMn37UG-PXYF",
      "https://drive.google.com/uc?export=download&id=1QSzMplL_Y4ZEauySHYfF7PsDooSkY5YH",
      "https://drive.google.com/uc?export=download&id=1wiUj4NYzxheGsq5sze1pfJZ1T7ZLieMJ",
      "https://drive.google.com/uc?export=download&id=1D-x924no93QbiN8txW1cadAvhkUySB58",
      "https://drive.google.com/uc?export=download&id=17QKudotHF_1vlMckMTf0dPvLBlpoL0wk",
      "https://drive.google.com/uc?export=download&id=1xUB3KGUwSzsY6V1qESGQyXIaDlb12RC8",
      "https://drive.google.com/uc?export=download&id=1SGRsnaqwTAUHRKfgbQ1peQ0CtJV2ZMZN",
      "https://drive.google.com/uc?export=download&id=1M7Olc8GUNuP6RIb4_s8ADeu7_OpdV6Pk",
      "https://drive.google.com/uc?export=download&id=1aZfctVIHBvipyOEZoeZOAvab_UjX36pS",
      "https://drive.google.com/uc?export=download&id=1OItHNXYdwipBDkV81wz2R3DiH4nFn57k",
      "https://drive.google.com/uc?export=download&id=1YYK9wKtY8L8AoUaLi0nvoMW_YcRUZzI5",
      "https://drive.google.com/uc?export=download&id=1k5p5yDocov-ZXFoKSdM9BMnMcHhNTjCA",
      "https://drive.google.com/uc?export=download&id=1XtuHzMJU00OlmWeazNkuiHBWY1wZz1qS",
      "https://drive.google.com/uc?export=download&id=1RU2lgYg-hNWkfYHsLlim_5QY2WKnO-_s",
      "https://drive.google.com/uc?export=download&id=1PKpK_-UvSHuow3b5i8W0TIMehhJBfPAL",
      "https://drive.google.com/uc?export=download&id=1HVTF6emzw9BqIrby4Myg17H2vtAOR3LI",
      "https://drive.google.com/uc?export=download&id=1rm-zSBnWnw3n8OzBch7tS-pgh54J17v_",
      "https://drive.google.com/uc?export=download&id=1sUBJJQpmF8JQRXmq7_XFghYdZRMDCEzU",
      "https://drive.google.com/uc?export=download&id=18ICsmkZsn5UbP3g9dxOo-blNe2HH8yay",
      "https://drive.google.com/uc?export=download&id=1kAtDcA5U-cRtskrMmxD3xXC_7v0Yczln",
      "https://drive.google.com/uc?export=download&id=1A2wf79EVEhVSWfzxbcJGJf5PHuvBdqDE",
      "https://drive.google.com/uc?export=download&id=1rSXGagJAMy5ovpN1JNvp7tF1HpHQvo_x",
      "https://drive.google.com/uc?export=download&id=1OGwRlpBQ24EeHclEtIW0jV6c4gP-CQXD",
      "https://drive.google.com/uc?export=download&id=1J0MtPjkQWbbgIqujVdl59vPZRK4-K-vv",
      "https://drive.google.com/uc?export=download&id=14vUVZa6p4pNpUeB98unlQG46s6-OjD_l",
      "https://drive.google.com/uc?export=download&id=14FgYCRFiQ4iO0xjSI5GA1JOk8nukiPY_",
      "https://drive.google.com/uc?export=download&id=1ggmmi0pV6AlePPq7bvjVLmMeBOzbtaG2",
      "https://drive.google.com/uc?export=download&id=1Wgble8e6q51PBrIprwe05PNWBv_u5jtC",
      "https://drive.google.com/uc?export=download&id=1Eevj2y7UMWqMyp1ZOUjwcZeP0-6AwLlt",
      "https://drive.google.com/uc?export=download&id=1KG3v8LCv3G3gcdHyLqf9h_8L6uj2wRbG",
      "https://drive.google.com/uc?export=download&id=1BO31sM78aDIKlSMAc7cx0EZgKR_9MONd",
      "https://drive.google.com/uc?export=download&id=1dmVXgkcwREpEbc3wuBjmyA43I2Zs6dTW",
      "https://drive.google.com/uc?export=download&id=1vvL5NqPlH7sLjhUwlf9NfJge4vTaB2R-",
      "https://drive.google.com/uc?export=download&id=1CS0Sq2Ij91zQDlGpmsNSzrl6hf4nKNR-",
      "https://drive.google.com/uc?export=download&id=1kNK8jmNDlrFbrnKCqtQeWU0cNJnsCbLg",
      "https://drive.google.com/uc?export=download&id=1kYapHPL_a31TeFFKNbCOBp6OzbSfsPIr",
      "https://drive.google.com/uc?export=download&id=17jP_cJVzlsQJI3-U4FTsClyc9OfME9iP",
      "https://drive.google.com/uc?export=download&id=1-4qwbcpd0dTfIfHns9mGMngjs3Ll0qat",
      "https://drive.google.com/uc?export=download&id=1PeBv0gQ8HE1pGCfFxl-xy5YWfLF3OQwe",
      "https://drive.google.com/uc?export=download&id=1nd2MtLzaig5atnKc7L3FPh7K52RT2lRP",
      "https://drive.google.com/uc?export=download&id=17q_8y8ekx6j1pVdkBgrrUxnxqkQiX1aF",
      "https://drive.google.com/uc?export=download&id=1v5CzdRVbW5D5uhGZQpUsckSl7ClmDGZx",
      "https://drive.google.com/uc?export=download&id=1mTQmG9bA4pVYRMEqxr5vE9G61gTZMFMI",
      "https://drive.google.com/uc?export=download&id=18ySI2JfWU9bFFyqtHdp86H5JYVwNP7r8",
      "https://drive.google.com/uc?export=download&id=1u-N_0TbLRrgy5fLS1zsC5vdCzX5ll38d",
      "https://drive.google.com/uc?export=download&id=1ChehrBzGKlcwxOtrQDZIGWE2WprI09dn",
      "https://drive.google.com/uc?export=download&id=1Y1-EcGhdqezf9sfSNB_kr2VI2DR1huT5",
      "https://drive.google.com/uc?export=download&id=1mEz0I6J8-l_3Ro9owFbT8w8nVhRkrhY2",
      "https://drive.google.com/uc?export=download&id=1I3aLa6qDJm014RQUMX7_nDaZk9IvNr8n",
      "https://drive.google.com/uc?export=download&id=12mWGHuz7Mz6FyhTTAC0KXX21p67nEBQ4",
      "https://drive.google.com/uc?export=download&id=1Pq562EwTzzf_pKMD16CJE-zlfwPqlWEv",
      "https://drive.google.com/uc?export=download&id=1tTiFwFsXTWlJ-XFADdEwhBGgDDcTlXp4",
      "https://drive.google.com/uc?export=download&id=1U361xb_t4YeZp1nljtYAqyzUEcUPDBfP",
      "https://drive.google.com/uc?export=download&id=1AkpoiSORsi8aJOwf_Zrfiatxwivxc_Q5",
      "https://drive.google.com/uc?export=download&id=1ZKpZKnRrWd2ulJUgSz9EBAR1vAgvfOTj",
      "https://drive.google.com/uc?export=download&id=1dnhJolTdhppg2axPU5uPpshVj2aJIXGv",
      "https://drive.google.com/uc?export=download&id=1ISt4eardedt_jzt5DG6yUZYNewlgeA1v",
      "https://drive.google.com/uc?export=download&id=1b1y85C3VH9RqnzPfHizJPHgcpA1xzzJH",
      "https://drive.google.com/uc?export=download&id=1bgE6x9WFA40lpOyvx_j95Vwlr2ATeKwD",
      "https://drive.google.com/uc?export=download&id=11K-4AIKjATdEs2KVjs80GYES-t7tfbZF",
      "https://drive.google.com/uc?export=download&id=1lLm_Vgz9KuzLLTSs45UNy0_ciK1TSMEi",
      "https://drive.google.com/uc?export=download&id=1f6tW4wCp_VcSuEH2VNlUR65F7kxjunPl",
      "https://drive.google.com/uc?export=download&id=1S1AvajHWJbUz8Ai0ryllbDXJsxj4IXl4",
      "https://drive.google.com/uc?export=download&id=1pzPgxzExBWOw9hBR198N_vJIQOMR7T38",
      "https://drive.google.com/uc?export=download&id=1MU5y4s5N6U0TWl7jGNUiGiaX30IWtcmr",
      "https://drive.google.com/uc?export=download&id=1U7lWd8_Yt6v1gBpAB8QjFnbiEJhAlpwf",
      "https://drive.google.com/uc?export=download&id=1lagvs5D3NGop-JqUqyD_UoXiscJ94s6T",
      "https://drive.google.com/uc?export=download&id=1RhHqKseLdnl8wJJ8wJldDCTH0XBE5PDN",
      "https://drive.google.com/uc?export=download&id=1EUteOHbxHJL5yJG6gOPFNGMEpoyXD28i",
      "https://drive.google.com/uc?export=download&id=1OjucETdkkMnsMS8OJDruD4s0AfYET0ed",
      "https://drive.google.com/uc?export=download&id=15dk9a6x198DLvcTn73FpWQS8GMyrTF7l",
      "https://drive.google.com/uc?export=download&id=1tSvNO_BmFEoZjKulGOo5yJgwkgoB1Tqm",
      "https://drive.google.com/uc?export=download&id=15s0vQ5a-hMhjPAGrNccVwwal4OKu2J_O",
      "https://drive.google.com/uc?export=download&id=1F3j_cN9po0wb9iCt-hL0wbPVxYeDjJuO",
      "https://drive.google.com/uc?export=download&id=1UDBz-Sia1PIIdq-6JAr0e_WkEOrYg9mT",
      "https://drive.google.com/uc?export=download&id=10iOSOE3his6hzLDJhjsdPcsxjnw9sVZk",
      "https://drive.google.com/uc?export=download&id=1plwq0F-XlNIxp87lakJFUA4hlxhtwveo",
      "https://drive.google.com/uc?export=download&id=1tbuuBQcFISOPpxNGQ2Zu45p5b_mSF3ZA",
      "https://drive.google.com/uc?export=download&id=1ja4anO4i8sBUy5387LfF397FLGO9pPTZ",
      "https://drive.google.com/uc?export=download&id=1nZ4vpR2hh_Y_T_h7PuE_dFaVedQ8SAps",
      "https://drive.google.com/uc?export=download&id=12Fl88qCBJw2gw9opZIVeUzn8kx2aFRA9",
      "https://drive.google.com/uc?export=download&id=1Ypb6KN80YMA2u5ayJotxvOafZYcdAyG9",
      "https://drive.google.com/uc?export=download&id=1l3B9LiRqwZDDhPdhkPZKpPvbeC8pasMW",
      "https://drive.google.com/uc?export=download&id=1t_FDpyUSWELHTyf7qkwsIVGDHV1duAf9",
      "https://drive.google.com/uc?export=download&id=1ZKgJUhqH3A66pGtaHOxxI4liGVad8759",
      "https://drive.google.com/uc?export=download&id=1iY8QuxD-XN0L5FJfagdss_9L4QQyAYAM",
      "https://drive.google.com/uc?export=download&id=1y0_z5CqgmdJgSYNWkXo-IZ6UygssG3qL",
      "https://drive.google.com/uc?export=download&id=1ueXeDajTk0nVq1k-8NO3gA4sx6Dp0Qr_",
      "https://drive.google.com/uc?export=download&id=1CqS3WEdfmZaUuY9DLkWcP6_HCkP-O0YP",
      "https://drive.google.com/uc?export=download&id=1kFxfd5Kqck614oLmOErmDF-e2hU-s9Ge",
      "https://drive.google.com/uc?export=download&id=1Y_zCu12BQlnu7jmRtaHxo08jZG-oC22G",
      "https://drive.google.com/uc?export=download&id=14QalCL2T6idQJUe5iFPzGBNNIZsdAF0b",
      "https://drive.google.com/uc?export=download&id=1kLnNiLP2gx7mHvbHzprJDwSwBM-8Ukzt",
      "https://drive.google.com/uc?export=download&id=1DpEpbXZq7INIPAXO_qn6PhvHtz30v2zy",
      "https://drive.google.com/uc?export=download&id=1-YVI9jJQxsZjxf4idYst0zCTikPNJeeQ",
      "https://drive.google.com/uc?export=download&id=1yIBZiv3N9Phe7odJG-IrXryLyQTvYJkc",
      "https://drive.google.com/uc?export=download&id=1wrDfSFZ41b0QP8abGHH_wEiBz0TuikCZ",
      "https://drive.google.com/uc?export=download&id=1EsTRAep8i87xmqzaFyWOIlZ9jhUopnrQ",
      "https://drive.google.com/uc?export=download&id=1d1hxX2zr-4yn-XYIzV6e_p91GJf78nFF",
      "https://drive.google.com/uc?export=download&id=12fflpUUqC0QCMk0hiwL6tf29KgZpMp3I",
      "https://drive.google.com/uc?export=download&id=1Gweiyvkr4v40SZAUjs0C3ImmoSFm9KSj",
      "https://drive.google.com/uc?export=download&id=11pFZiJUT-Iv71-YMkmOL59hY7j3phBDH",
      "https://drive.google.com/uc?export=download&id=11PnoqPLH5yjggAG1fiwcgSWrd6jY3net",
      "https://drive.google.com/uc?export=download&id=1Z8rlFimEVVJbgK_Myd8CCjisF6Eq_5Vf",
      "https://drive.google.com/uc?export=download&id=1z_MIHtMbnfZGYAdOS1feuq3C0hgaYP-s",
      "https://drive.google.com/uc?export=download&id=1DJk9XRq2hY2GVpfnanuk6t9Z5gIw5-Dk",
      "https://drive.google.com/uc?export=download&id=1bIH5U6SERbQMD6oIINK24Inn8AxA_qQA",
      "https://drive.google.com/uc?export=download&id=1pPQJr2bPIOBjqci5IWZR9XAtgCidACKL",
      "https://drive.google.com/uc?export=download&id=1n8R7fO4NxkkvmK4rXRlb7kHb8JwUykFi",
      "https://drive.google.com/uc?export=download&id=1-MzkP7ZeDbwj0b3rxZvrHllQqKmVwCI7",
      "https://drive.google.com/uc?export=download&id=1ylZKsOXXFHjxcUwl6OJb17ouWSaESM69",
      "https://drive.google.com/uc?export=download&id=1C-hz0eDnqjGRaYUQQrwE0BKD8QC6oUSN",
      "https://drive.google.com/uc?export=download&id=1Bqic0ZpyK2Qcx-kGd5vPyb0_rDXk4Ui_",// Add more video links here
    ];

    const availableVideos = link.filter(video => !this.sentVideos.includes(video));

    if (availableVideos.length === 0) {
      this.sentVideos = [];
    }

    const randomIndex = Math.floor(Math.random() * availableVideos.length);
    const randomVideo = availableVideos[randomIndex];

    this.sentVideos.push(randomVideo);

    if (senderID !== null) {
      message.reply({
        body: 'ENJOY..🤍',
        attachment: await global.utils.getStreamFromURL(randomVideo),
      });

      setTimeout(() => {
        api.unsendMessage(loadingMessage.messageID);
      }, 5000);
    }
  },
};